import type { StrategyCategory, StrategyMetadata, StrategyRiskLevel } from "@/domain/models";
import { meanReversionStrategy } from "@/strategies/mean-reversion";
import { momentumStrategy } from "@/strategies/momentum";
import { StrategyRegistry } from "@/strategies/registry";
import { weekendStrategy } from "@/strategies/weekend";
import { dcaStrategy } from "@/strategies/dca";

const comingSoon = (
  id: string,
  name: string,
  description: string,
  category: StrategyCategory,
  riskLevel: StrategyRiskLevel,
): StrategyMetadata => ({
  id,
  name,
  description,
  category,
  enabled: false,
  supportedAssets: [],
  riskLevel,
  requiredData: ["price"],
  supportedSessions: [],
  status: "coming_soon",
  version: "0",
});

/** Metadata only. These strategies are not registered and cannot be evaluated. */
export const COMING_SOON_STRATEGIES: readonly StrategyMetadata[] = [
  comingSoon("arbitrage", "Cross-representation arbitrage", "Differences between tokenized representations of one underlying. Not built.", "relative_value", "high"),
  comingSoon("earnings", "Earnings", "Scheduled earnings reactions. Not built.", "event", "high"),
  comingSoon("event", "News / event", "News and event reactions. Not built.", "event", "high"),
  comingSoon("volatility", "Volatility", "A standalone volatility book. Regime classification is separate and is implemented.", "research", "high"),
  comingSoon("relative-value", "Relative value", "Pairs and baskets. Not built.", "relative_value", "medium"),
  comingSoon("rebalancing", "Rebalancing", "Portfolio rebalancing. Not built.", "execution", "medium"),
  comingSoon("liquidity-execution", "Liquidity-aware execution", "Execution scheduling against depth. Not built.", "execution", "medium"),
  comingSoon("correlation", "Crypto / equity correlation", "Cross-asset correlation. Not built.", "research", "medium"),
  comingSoon("agent-generated", "Agent-generated", "Hypotheses generated by a research agent. Not built.", "research", "high"),
];

export function createStrategyRegistry(): StrategyRegistry {
  const registry = new StrategyRegistry();
  registry.register(momentumStrategy);
  registry.register(meanReversionStrategy);
  registry.register(weekendStrategy);
  registry.register(dcaStrategy);
  return registry;
}

export function listStrategyCatalog(registry: StrategyRegistry = createStrategyRegistry()): StrategyMetadata[] {
  return [...registry.list().map((strategy) => strategy.metadata), ...COMING_SOON_STRATEGIES];
}

export function getStrategyMetadata(id: string): StrategyMetadata | undefined {
  return listStrategyCatalog().find((strategy) => strategy.id === id);
}
