export type AgentEventType =
  | "MARKET_OBSERVED"
  | "HISTORY_UPDATED"
  | "FEATURES_UPDATED"
  | "REGIME_UPDATED"
  | "STRATEGY_EVALUATED"
  | "SIGNAL_CREATED"
  | "SIGNAL_REJECTED"
  | "INSUFFICIENT_DATA"
  | "STRATEGIES_EVALUATED"
  | "ARBITRATION_STARTED"
  | "CANDIDATE_ACCEPTED"
  | "CANDIDATE_REJECTED"
  | "STRATEGY_CONFLICT"
  | "STRATEGY_SELECTED"
  | "ARBITRATION_ABSTAINED"
  | "ARBITRATION_BLOCKED"
  | "TRADE_INTENT_CREATED"
  | "RISK_CHECK_STARTED"
  | "RISK_APPROVED"
  | "RISK_REJECTED"
  | "TRADE_INTENT_EXPIRED"
  | "PAPER_SIMULATION_STARTED"
  | "PAPER_SIMULATION_PASSED"
  | "PAPER_SIMULATION_FAILED"
  | "PAPER_EXECUTED"
  | "POSITION_UPDATED"
  | "POSITION_REVIEW_STARTED"
  | "POSITION_DECISION_RECORDED"
  | "POSITION_DECISION_HOLD"
  | "POSITION_DECISION_ADD"
  | "POSITION_DECISION_REDUCE"
  | "POSITION_DECISION_EXIT"
  | "POSITION_DECISION_BLOCKED"
  | "POSITION_INTENT_CREATED"
  | "POSITION_ADD_EXECUTED"
  | "POSITION_REDUCE_EXECUTED"
  | "POSITION_EXIT_EXECUTED"
  | "POSITION_CLOSED"
  | "WALLET_CHECK_STARTED"
  | "WALLET_CONNECTED"
  | "WALLET_POLICY_READ"
  | "WALLET_POLICY_BLOCKED"
  | "WALLET_EXECUTION_STARTED"
  | "WALLET_EXECUTION_SUBMITTED"
  | "WALLET_CONFIRMATION_REQUIRED"
  | "WALLET_EXECUTION_REJECTED"
  | "TRANSACTION_VERIFICATION_STARTED"
  | "TRANSACTION_CONFIRMED"
  | "TRANSACTION_VERIFICATION_FAILED";

export interface AgentEvent {
  id: string;
  type: AgentEventType;
  at: string;
  ticker: string | null;
  strategyId: string | null;
  message: string;
  userId?: string;
  agentId?: string;
  assetId?: string;
  correlationId?: string;
  intentId?: string;
  metadata?: Readonly<Record<string, string | number | boolean | null>>;
}
