/** Provenance labels. A later explanation cites these. They are not a ranking score. */
export const SOURCES = {
  BINANCE_RWA_API: "BINANCE_RWA_API",
  BINANCE_MARKET_CANDLES: "BINANCE_MARKET_CANDLES",
  BINANCE_TRADING_SIGNAL: "BINANCE_TRADING_SIGNAL",
  BINANCE_TOKEN_AUDIT: "BINANCE_TOKEN_AUDIT",
  BINANCE_TOKENIZED_SECURITY: "BINANCE_TOKENIZED_SECURITY",
  FMP_EARNINGS: "FMP_EARNINGS",
  FMP_NEWS: "FMP_NEWS",
  PAPER_SAMPLE: "PAPER_SAMPLE",
  KAIROS_FEATURE_ENGINE: "KAIROS_FEATURE_ENGINE",
  KAIROS_SESSION: "KAIROS_SESSION",
  KAIROS_STRATEGY_ENGINE: "KAIROS_STRATEGY_ENGINE",
  KAIROS_STRATEGY_HEALTH: "KAIROS_STRATEGY_HEALTH",
  KAIROS_PAPER_LEDGER: "KAIROS_PAPER_LEDGER",
  KAIROS_RESEARCH: "KAIROS_RESEARCH",
  QWEN: "QWEN",
} as const;

export type SourceName = (typeof SOURCES)[keyof typeof SOURCES];
